# VPATH := ../_share:../BST:../UniPrint:../huffman:../BinTree:../list:../:/Users/edz/work/cplus/dsacpp-vs2019.210216/src

#VPATH = ../UniPrint


out : main.cpp
	clang++ -std=c++11 -g -o $@ $^ 
	
	
 #print_basic.cpp print_HuffChar.cpp
#-I../

